### PR TITLE
Updated email template

### PR DESCRIPTION
**Pull request by valentinyanakiev**
- No unit tests added
- Reusing footer from a constant across all templates, the approach can be expanded further
- Builders need to be refactored / made generic

Other than that, works for me locally, preferences work and altogether notifications seem to work quite nicely with this set of updates

### CODE REVIEW

**Comment by techsmyth** [comment]
image

getting this error when trying to send emails...

**Comment by valentinyanakiev** [comment]
> image
> 
> getting this error when trying to send emails...

Built a container, included in the server stack, and ran the following query:

```
mutation createApplication($applicationData: CreateApplicationInput!) {
  createApplication(applicationData:$applicationData){
    id
  }
}
```

with data
```
{
  "applicationData": {
    "parentID": "07ee8814-0407-43b9-a1f6-f90615c1ed18",
    "userID": "301cc16b-f646-4a64-b1a8-216cd2b87c9d",
    "questions": [
      {"name": "Question 1", "value": "No", "sortOrder": 1},
      {"name": "Question 2", "value": "Yes", "sortOrder": 2},
      {"name": "Question 3", "value": "Maybe", "sortOrder": 3},
      {"name": "Question 4", "value": "Yes", "sortOrder": 4}
    ]
  }
}
```

settings:
image


result:
- mailslurper

image

-email
 - settings
```
ALKEMIO_SERVER_ENDPOINT=http://localhost:3000/admin/graphql
SERVICE_ACCOUNT_USERNAME=notifications@alkem.io --> Global Community Admin
SERVICE_ACCOUNT_PASSWORD=change-me-now
KRATOS_API_PUBLIC_ENDPOINT=http://localhost:3000/identity/ory/kratos/public
EMAIL_SMTP_HOST=email-smtp.eu-central-1.amazonaws.com
EMAIL_SMTP_PORT=587
EMAIL_SMTP_SECURE=false
EMAIL_SMTP_USER=[SMTP_USER]
EMAIL_SMTP_PASSWORD=[SMTP_PASS]
EMAIL_MULTI_PROVIDER_STRATEGY=no-fallback
```

stopped notifications container, re-ran the query, result:
image

**Review by techsmyth — APPROVED** [review]
Nice to have this in!

**Comment by techsmyth** [comment]
Merged separately

**Pull request closed without merging**
